codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 20%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 50%
        threshold: 5%

# Flags for different test tiers - Codecov merges coverage from all flags
flags:
  unit:
    paths:
      - "!**/*_test.go"
    carryforward: true
  integration:
    paths:
      - "!**/*_test.go"
    carryforward: true
  e2e:
    paths:
      - "!**/*_test.go"
    # Critical: carry forward when e2e doesn't run on PRs
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
