codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        # Start at current baseline (24.6%), increase gradually
        target: 20%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        # New code should be reasonably tested
        target: 50%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
